CREATE TABLE SINGER_TB (
       ID_TB INT NOT NULL AUTO_INCREMENT
     , FIRST_NAME_TB VARCHAR(60) NOT NULL
     , LAST_NAME_TB VARCHAR(40) NOT NULL
     , BIRTH_DATE_TB DATE
     , UNIQUE UQ_SINGER_1 (FIRST_NAME_TB, LAST_NAME_TB)
     , PRIMARY KEY (ID_TB)
)

CREATE TABLE ALBUM_TB (
       ID_TB INT NOT NULL AUTO_INCREMENT
     , SINGER_ID INT NOT NULL
     , TITLE_TB VARCHAR(100) NOT NULL
     , RELEASE_DATE_TB DATE
     , UNIQUE UQ_SINGER_ALBUM_1 (SINGER_ID, TITLE_TB)
     , PRIMARY KEY (ID_TB)
     , CONSTRAINT FK_ALBUM FOREIGN KEY (SINGER_ID)
                  REFERENCES SINGER (ID_TB)
)